name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:

  build-and-test:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: install seqgibbs
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install coverage codecov
      - name: run coverage
        run: |
          coverage run run-tests.py --unit

      - name: codecov
        if: success()
        env:
          CODECOV_TOKEN: 1c20d55b-28ba-423a-aba9-18d55d84e271
        run: |
          codecov
